version: '3.7'
services:
  database:
    image: 'mongo'
    container_name: 'mongo-container'
    environment: 
      - MONGO_INITDB_DATABASE=cryptocurrencies_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root_pass
      - MONGO_USER=user
      - MONGO_PASS=pass
    volumes: 
      - ./mongo-volume:/data/db
    ports: 
      - '27017-27019:27017-27019'
  # app:
  #   build: .
  #   container_name: 'cryptocurrencies-container'
  #   ports: 
  #     - '3000:3000'
  #   environment: 
  #     - NODE_ENV=production
  #     - MONGO_DB_HOST=database
  #   depends_on: 
  #     - database